@startuml test

!define Devops https://raw.githubusercontent.com/xNok/devops-plantuml-sprites/main/components
!includeurl Devops/common.puml
!includeurl Devops/docker.puml
!includeurl Devops/caddy.puml
!includeurl Devops/dev.puml

DockerContainer(portainer, "Portainer")
CaddyServer(caddy, "name")

HappyDeveloper(dev, "Happy Dev")
EvilDeveloper(dev2, "Evil Dev")

@enduml