name: Deploy site to GitHub Pages

on:
  pull_request:
    # Only run when targeting main
    branches:    
      - main
    types:
      - opened
      - edited
      - ready_for_review
      - synchronize
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.108.0
      KROKI_VERSION: 0.5.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          # ssh-keygen -t ed25519 -C "git@github.com:mekitmedia/gethugothemes-thomson.git"
          ssh-key: |
            ${{ secrets.SSH_PRIVATE_KEY_THEME_THOMSON }}

      - name: Install Kroki
        run: |
          wget -O ${{ runner.temp }}/kroki.tar.gz https://github.com/yuzutech/kroki-cli/releases/download/v${KROKI_VERSION}/kroki-cli_${KROKI_VERSION}_linux_amd64.tar.gz
          tar -xvzf ${{ runner.temp }}/kroki.tar.gz
          chmod +x kroki

      - name: Generate diagrams
        run: |
          docker-compose up -d
          sleep 20
          python ./scripts/render_diagrams.py

      - name: Archive rendered images
        uses: actions/upload-artifact@v3
        with:
          name: images
          path: website/static/images/gallery

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Build TinaCMS
        env:
          TINA_PUBLIC_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
        run: |
          cd website
          npm install
          npm run tinacms

      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          cd website
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
       
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./website/public

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
